; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Colour Scraper"
#define MyAppVersion "1"
#define MyAppPublisher "Kyle Tichon"
#define MyAppURL "https://github.com/ktichon"
#define MyAppExeName "colour_scraper.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{43E4A60E-C1DF-4C71-911E-8C22200495D2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputBaseFilename=Colour-Scraper-Installer
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_asyncio.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_bz2.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_ctypes.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_decimal.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_hashlib.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_lzma.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_multiprocessing.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_overlapped.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_queue.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_socket.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\_ssl.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-console-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-datetime-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-debug-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-errorhandling-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-file-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-file-l1-2-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-file-l2-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-handle-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-heap-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-interlocked-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-libraryloader-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-localization-l1-2-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-memory-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-namedpipe-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-processenvironment-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-processthreads-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-processthreads-l1-1-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-profile-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-rtlsupport-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-string-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-synch-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-synch-l1-2-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-sysinfo-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-timezone-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-core-util-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-conio-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-convert-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-environment-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-filesystem-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-heap-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-locale-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-math-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-process-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-runtime-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-stdio-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-string-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-time-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\api-ms-win-crt-utility-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\base_library.zip"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\colour_scraper.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\libcrypto-1_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\libffi-7.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\libssl-1_1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\pyexpat.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\python310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\select.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\ucrtbase.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\unicodedata.pyd"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\dist\colour_scraper\VCRUNTIME140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\Analysis-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\base_library.zip"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\COLLECT-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\colour_scraper.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\colour_scraper.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\colour_scraper.pkg"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\EXE-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\PKG-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\PYZ-00.pyz"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\PYZ-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\Tree-00.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\Tree-01.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\Tree-02.toc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\warn-colour_scraper.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\build\colour_scraper\xref-colour_scraper.html"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\Red_River\term_5\Python\Assignment_8\__pycache__\colour_scraper.cpython-310.pyc"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

